Fixed Samba Move Object
go-ldap/ldap pull request #286
Opened 2020-10-12 20:30 UTC by ZDuygu

This pr fixes #194

2020-10-12 20:31 UTC, mertcelen commented
We need this pr to merged ASAP.

2020-10-13 00:08 UTC, stefanmcshane requested changes
A few minor changes to be made before approval
Tag me and I will help get this approved for you asap

2020-10-13 00:08 UTC, stefanmcshane commented on moddn.go
> +//	pkt.AppendChild(ber.NewBoolean(ber.ClassUniversal, ber.TypePrimitive, ber.TagBoolean, req.DeleteOldRDN, "Delete old RDN"))
Please remove the commented code from the PR

2020-10-13 00:08 UTC, stefanmcshane commented on go.mod
> +module github.com/Zduygu/ldap
Please revert this to the original name - I understand that this was for testing

2020-10-13 00:08 UTC, stefanmcshane commented on v3/go.mod
> +module github.com/ZDuygu/ldap/v3
Please revert this change - I understand it was for testing

2020-10-13 00:08 UTC, stefanmcshane commented on moddn.go
> +//	pkt.AppendChild(ber.NewBoolean(ber.ClassUniversal, ber.TypePrimitive, ber.TagBoolean, req.DeleteOldRDN, "Delete old RDN"))
Please reflect this change in the v3/ folder also

2020-10-13 00:08 UTC, stefanmcshane commented on go.mod
> +module github.com/ZDuygu/ldap
Please revert this change - I understand it was for testing

2020-10-13 06:56 UTC, mertcelen commented
@stefanmcshane changes applied :)

2020-10-13 20:49 UTC, mertcelen commented
@stefanmcshane you are absolutely right to ask for tests but if you check closer, there seems to be a bug with older go version tests itself. If I'm not wrong, it has nothing to do with our change. I'll gladly help if that's the case but since you flagged them as legacy and google obviously dropped support for it https://golang.org/doc/devel/release.html#policy we may as well just delete those.

Your call.

2020-10-13 21:16 UTC, stefanmcshane commented
@mertcelen Whilst I wouldn't use Go's release history as an argument as the scopes are very different, I would agree that we should review the supported legacy versions going forward. This would need to be done as a separate PR, before merging this change.

@johnweldon Opinions on this? We would be potentially breaking backwards compatibility for any Go versions <= 1.6 (released 2016, support dropped 2017). 
However, I would suggest dropping support for 1.5 and 1.6 in a new PR, tagging as a hotfix release (v3.2.4), then merging this PR.

Aside: This would also provide a strong segue for tidying go modules up further, by dropping support for non-module installation, and making the new default branch "v3". If you agree to the above, I'll open a new issue for discussion on go module related updates.

2020-10-14 19:29 UTC, stefanmcshane approved these changes

2020-10-14 19:29 UTC, merged

2020-10-14 19:32 UTC, stefanmcshane commented
@mertcelen @ZDuygu This has been tagged v3.2.4 and released. Thank you for your contributions and patience!