Change debugger to write packet via log's Writer (#1)
go-ldap/ldap pull request #306
Opened 2021-01-26 17:33 UTC by almozavr

## Issue

Debugger prints debug-level messages via std `log` but prints packets via `os.Stdout`, so it makes impossible to use the `Output` from the global `log`, e.g. `zap` provides [single point of configuration even for the global `log`](https://godoc.org/go.uber.org/zap#RedirectStdLog), so still could be used for libraries logging setup.

## Solution

Pass `log#Writer()` to the `ber` packet writer func.

Partly resolves https://github.com/go-ldap/ldap/issues/164

2021-03-30 21:00 UTC, stefanmcshane requested changes
Please apply these changes to debug.go as well as v3/debug.go in order to merge.
Ill review this weekend to get them merged then!

Thanks,
Stefan

2021-04-07 21:19 UTC, stefanmcshane approved these changes

2021-08-15 01:53 UTC, johnweldon approved these changes
LGTM; please update with master and we'll merge it in.

2021-08-16 09:33 UTC, almozavr commented
@johnweldon updated 👍 also, I've prettified commits a bit

2021-08-16 19:58 UTC, johnweldon approved these changes
LGTM; thank you!

2021-08-16 19:58 UTC, merged

2021-08-23 12:44 UTC, lozbrown commented
@johnweldon @almozavr 

This change seems to have broken an automated install for me, the go get command now gives the following error. 

"go/src/github.com/go-ldap/ldap/debug.go:28:19: undefined: log.Writer"

2021-08-23 12:50 UTC, johnweldon commented
> This change seems to have broken an automated install for me, the go get command now gives the following error.
> 
> "go/src/github.com/go-ldap/ldap/debug.go:28:19: undefined: log.Writer"

can you specify exactly what your `go get` invocation is, as well as the version of Go you're using?