Improve search attribute extraction
go-ldap/ldap pull request #321
Opened 2021-04-08 19:27 UTC by xNevo

@stefanmcshane  As mentioned in #319, here's my PR for improving the part of the attribute extraction after an LDAP search result has been returned by the server. 

I did [some benchmarks](https://gist.github.com/xNevo/e4faf1a90bb610e59ec622e3e6e62558), as requested. The differences become more significant the more attributes are parsed. Regardless of the performance: I think this code should be moved into it's own fucnction anyway for better readability.

2021-06-30 18:12 UTC, xNevo commented
May someone please look into this?

2021-08-12 16:59 UTC, xNevo commented
@johnweldon  Is there a chance that this PR will be reviewed/merged?

2021-08-12 17:33 UTC, johnweldon commented
> @johnweldon Is there a chance that this PR will be reviewed/merged?

😞 I'm sorry for neglecting this. I'll review shortly

2021-08-15 01:31 UTC, johnweldon requested changes
LGTM; if you could address the minor whitespace issues, and rebase, I'll get this merged.

2021-08-15 01:31 UTC, johnweldon commented on search.go
> +	ber "github.com/go-asn1-ber/asn1-ber"
Minor nit, keep third party imports as a second import group, rather than mixed in with the stdlib imports.

2021-08-15 01:31 UTC, johnweldon commented on search.go
> +	}
I don't mind trivial whitespace changes like this, but I'd prefer if we keep them consistent between the root version and the `v3/` version

2021-08-15 02:21 UTC, johnweldon approved these changes

2021-08-15 02:21 UTC, merged